### ISSUE TITLE
A4 maybe?

### ISSUE THREAD

**Issue by SidneyBovet** [Denwid/pcml-cheatsheet#5]
None of my buisness since I am not enrolled in PCML, but your document looks like being in US Letter format.

Add the `a4paper` option to your `geometry` package to gain more space (and mess up with your formatting ;) )

As one would say, gl&hf!

**Comment by Denwid** [comment]
First line of the file: `\documentclass[10pt,a4paper,landscape]{article}` ;-)

**Comment by SidneyBovet** [comment]
Haha I must be blind or something x) sorry about that

**Comment by merlinND** [comment]
Thanks for taking the time to have a look though!
